/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_UC_Backend_Extra_RangeChecker */

#ifndef _Included_com_example_UC_Backend_Extra_RangeChecker
#define _Included_com_example_UC_Backend_Extra_RangeChecker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_UC_Backend_Extra_RangeChecker
 * Method:    getAgentsInRange
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_UC_1Backend_Extra_RangeChecker_getAgentsInRange
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
